### ISSUE TITLE
xxx was not declared in this scope, which library did the error come from?

### ISSUE THREAD

**Issue by KesarChi** [Zilong-Li/vcfpp#1]
hi author, when i build&run your test code, it raised some errors such as: ‘kputd’ was not declared in this scope;  ‘bcf_has_variant_types’ was not declared in this scope.  where did the error come from? Is it because i failed to import any library? thx
![屏幕截图 2024-09-26 192118](https://github.com/user-attachments/assets/c863eb87-1d20-4fe3-984f-ae9ea2947789)

**Comment by Zilong-Li** [comment]
Hi, can you show your compiling command? Also, do you have https://github.com/samtools/htslib/tree/develop installed system-wide? 

Thanks

**Comment by KesarChi** [comment]
Thx！i think it's due to lib env conflict, now it works😀
